name: Build and Publish Docker Images

on:
  push:
    branches: [ master ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Publish Docker Image android33java11
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./android33java11/.
          push: true
          tags: gowthamraj07/android33java11:latest

      - name: Get the Docker Image Digest
        id: docker_digest
        run: echo ${{ steps.docker_build.outputs.digest }}
